name: Build and Deploy to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: asisserver/tictactoews:latest

    - name: Verify Pushed Image
      run: docker pull asisserver/tictactoews:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }} 
        script: |
          sudo docker pull asisserver/tictactoews:latest
          sudo docker stop tictactoews || true
          sudo docker rm tictactoews || true
          sudo docker run -d --name tictactoews -p 7079:7079 --restart always \
          -e SECRET_KEY=${{ secrets.SECRET_KEY }} asisserver/tictactoews:latest
